/******************************************************************************
*
* Copyright (C) 2015-2023 Allegro DVT2
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in all
* copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*
******************************************************************************/

// This file was generated by configure. DO NOT MODIFY


#ifndef AL_DEC_NUM_CORES
#define AL_DEC_NUM_CORES 2
#endif
#ifndef HW_IP_BURST_ALIGNMENT
#define HW_IP_BURST_ALIGNMENT 32
#endif
#ifndef AL_MAX_ENC_SLICE
#define AL_MAX_ENC_SLICE 200
#endif
#ifndef AL_LOG_LEVEL
#define AL_LOG_LEVEL 0
#endif
#ifndef MAX_NUM_LAYER
#define MAX_NUM_LAYER 1
#endif
#ifndef AL_TITLE
#define AL_TITLE XilinxVDU
#endif


#define AL_CONFIGURE_COMMANDLINE "./configure --config-blob customers/XilinxVDU/config.ini"
#define AL_VERSION_MAJOR 0
#define AL_VERSION_MINOR 34
#define AL_VERSION_STEP 0

